### ISSUE TITLE
Build the events pane into the application

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#10]
The task is to build out just the UI for the events portion of the application. 
The idea is:
- Build the UI for the event 
- Feel free to isolate the different size cards as their own components for usability.
- All components should be in the components folder to avoid Merge conflicts

The UI looks like this:
![events](https://user-images.githubusercontent.com/26451435/174810609-e414cdff-6017-4286-9d55-da82137c0dc8.png)

**Comment by steekam** [comment]
Hey, I can handle this one.

**Comment by katungi** [comment]
That's awesome. You can start with building the UI first for now as we move on.

**Comment by Lekipising** [comment]
Hey @katungi any more pending designs?

**Comment by katungi** [comment]
Hey @Lekipising , could you create an issue so we can discuss this there? I wanted to close this issue.

**Comment by Lekipising** [comment]
Sure @katungi
