### ISSUE TITLE
The Navbar is Not Well Responsive

### ISSUE THREAD

**Issue by marthamwangi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#14]
@katungi Navbar looks like 👇 , can I fix this one?
![image](https://user-images.githubusercontent.com/37874101/174939474-4b06848e-0385-4991-9206-fa81ce210ed5.png)

**Comment by katungi** [comment]
Hey @marthamwangi, yes yes you can take on the issue and fix it.
While at it, you can convert the routes to use the inbuilt Next.js routing. 
In case you need reference, here are the [docs](https://nextjs.org/docs/routing/introduction), they are pretty straightforward.

Have fun :-)

**Comment by marthamwangi** [comment]
Aye! aye! captain.

**Comment by marthamwangi** [comment]
@katungi, the Nav.js is overriding the Nav.tsx.
The Nav.js file should be removed

**Comment by katungi** [comment]
Nice catch @marthamwangi, I was wondering what's breaking the Nav. Was almost sending you an email. Bless you. I have fixed the issue and pushed to `develop`. ⚡⚡
