### ISSUE TITLE
Animate landing page value proposition header

### ISSUE THREAD

**Issue by alexmagwe** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#15]
## request to add text typing animation to  the "learn, grow, connect" header in the landing page

![she-code](https://user-images.githubusercontent.com/47972920/175105298-d0814aa3-2813-491f-aa86-39910ed7595e.jpg)

**Comment by alexmagwe** [comment]
@katungi let me work on this

**Comment by katungi** [comment]
Merged the conflicts @alexmagwe , and merged to develop. Sorry it took so long!
