### ISSUE TITLE
Refactor to use Layout

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#22]
Next Js comes with a handy feature that allows you to add a static layout to all pages.
Could be a good idea to potentially move `Nav` and `Footer` components to be in the layout component so that all pages will have a footer and a Nav.

**Comment by Mogakamo** [comment]
@katungi can I work on this

**Comment by katungi** [comment]
Hey, year sure. Take a stab at it. It's a simple issue so I don't expect it should take time.

**Comment by Mogakamo** [comment]
cool @katungi working on it now

**Comment by katungi** [comment]
Amazing work @Mogakamo . Thanks for the good work!
