### ISSUE TITLE
Fix the padding and spacing between call to action and the events components

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#23]
These 2 components were well done but have some issues. The purpose of this task is to streamline the following issues"
- The order according to the design should be, the `call to action` then then events `components`. Currently, it's the other way round. 
- They should have tge same padding and be aligned especially on bigger devices
- On mobile their is some space between these 2 components that's not needed. It's too big. It should be removed
- Finally, the Call to action component should have rounded corners

Anyone willing to fix these issues?

**Comment by CatherineKiiru** [comment]
I'd like to take this issue

**Comment by katungi** [comment]
Hey @CatherineKiiru , seems that @machariavck has already raised a PR for this issue.

**Comment by katungi** [comment]
Hey @CatherineKiiru, I have created 2 new issues, you can check them out and pick one that you fancy!
