### ISSUE TITLE
Create the Nav-Bar For the website

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#3]
To kick the website off, let's create the Nav-bar
- The navbar should match the design
- The navbar should be responsive

It will be nice to use Tailwind to style the nav so it's easier to make mobile friendly. 

N/B Refer to the designs on Figma when creating it.

**Comment by 3stherMueni** [comment]
Hey @katungi, I would love to work on this

**Comment by katungi** [comment]
Sure thing, have a go at it 🥳

**Comment by katungi** [comment]
Amazing work @3stherMueni , I merged into main.
