### ISSUE TITLE
Dark mode for SheCodeAfrica-Nairobi-Website

### ISSUE THREAD

**Issue by zidanegimiga** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#30]
Hello! I'm suggesting that we add a dark mode for the website. Here's a modification I made using Figma. I'm requesting editing access if you like this.
[Link to prototype](https://www.figma.com/proto/iMbVCdA8ntgFiTSdslF3Vr/She-Codes-Africa-Nairobi-(Copy)?node-id=802%3A1095&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=11%3A18) 

![she-code-dark-mode-conribution (1)](https://user-images.githubusercontent.com/33351058/177732866-bcbeda55-45c2-4fcd-9120-66ceac46dd5c.gif)

![image](https://user-images.githubusercontent.com/33351058/177735460-e69909e8-2cfd-4aa1-829d-9928b27e9a4e.png)

**Comment by katungi** [comment]
This is a really great initiative. Love it!!
@M-Tee, can you check this out??

**Comment by M-Tee** [comment]
This is pretty cool. Love it.

**Comment by M-Tee** [comment]
@zidanegimiga I can't find your email on Github. Could you share it

**Comment by zidanegimiga** [comment]
> @zidanegimiga I can't find your email on Github. Could you share it

Sorry about that, it's zidanegimigatemp@gmail.com

**Comment by M-Tee** [comment]
I've sent an edit invite to the Figma file you can copy and paste dark mode.

**Comment by bettttttttttt** [comment]
@katungi 
The site but done in Angular

**Comment by katungi** [comment]
Hey @bettttttttttt, I love what you did with Angular, if only our site was done in angular. Regardless, we could definitely do the same. 
This is issue is up for grabs. The idea is to have a toggle button that allows one to choose either dark or light mode, but by default it goes with the user's device theme.

**Comment by bettttttttttt** [comment]
@katungi I'm just doing it with Angular for fun. 
Anyway, I've added a skeleton loader on the events page, and the search input on the same page has a dynamic placeholder which I think is cool!

**Comment by katungi** [comment]
Wait, you did all those in angular still??

**Comment by bettttttttttt** [comment]
@katungi Yes, everything I'm doing is in Angular
I'll share the repo by the end of the day

**Comment by katungi** [comment]
Cool, I will make sure to give you a shoutout for your amazing work @bettttttttttt 👏🏿👏🏿

**Comment by katungi** [comment]
I will close this for now and re-create a new issue for this so it can be worked on by someone else.
