### ISSUE TITLE
Fix images on the Events Components

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#36]
The dynamic images are scaling wrongly on the events component, 
This is a small issue that's a good first issue 👏🏿

**Comment by fosa-ij** [comment]
hey @katungi i would like to work on this issue

**Comment by fosa-ij** [comment]
Nevermind @katungi

**Comment by katungi** [comment]
Hey @fosa-ij , still interested in working on the issue??

**Comment by DreMukare** [comment]
Hey @katungi 
Gimme more insight on the bug

**Comment by katungi** [comment]
Hey @DreMukare , So on the events component, the images look bad. Ideally, they should fit the image component as per the design. So the task will be to make those images from the events data play well within the images.
Also, if you are feeling energetic and want to explore, you can try refactoring from the native `img` tag to using Next's [Image tag](https://nextjs.org/docs/api-reference/next/image).

Can you handle this?

**Comment by DreMukare** [comment]
Yes i can :)

**Comment by katungi** [comment]
Hey @DreMukare , any update on this issue?

**Comment by johnGachihi** [comment]
@katungi I'd like to continue with this

**Comment by katungi** [comment]
Hey @johnGachihi , yeah sure thing - go on and work on it.

**Comment by johnGachihi** [comment]
@M-Tee, @katungi Eventbright uses landscape images but the event card design is for square images. The options I see for dealing with this mismatch are stretching and cutting the images to fit the square cards (which is how it is now) or rendering the images in landscape and filling the remaining space in the square cards like below.

What do you think? Should we go with one of these?

![Screenshot from 2023-01-17 15-18-20](https://user-images.githubusercontent.com/25545884/212903410-5d43f607-4d66-474e-b4fe-edb6c0c26d34.png)

![Screenshot from 2023-01-17 15-07-02](https://user-images.githubusercontent.com/25545884/212903537-827296da-df09-42cf-8708-6f2d9745d6d4.png)

![Screenshot from 2023-01-17 15-36-33](https://user-images.githubusercontent.com/25545884/212903619-bb635470-f21a-4b77-ade5-2c10170ca122.png)

**Comment by johnGachihi** [comment]
@katungi I've tried playing around with the last option but it's leaving a lot of empty space which doesn't look good, especially on tablet-size screens. @M-Tee your opinion would really be appreciated.

**Comment by katungi** [comment]
Hey @johnGachihi , could you send a screenshot?

**Comment by johnGachihi** [comment]
These are both on screen width 820px. The problem is mainly on the large event card

With the original layout
![Screenshot from 2023-01-20 19-20-48](https://user-images.githubusercontent.com/25545884/213751441-d186cc4c-829b-4635-bec3-0dedcd1c7f14.png)

With a different layout meant to reduce the size of the large event card
![Screenshot from 2023-01-20 19-30-34](https://user-images.githubusercontent.com/25545884/213752264-8445e90d-e94c-45fd-847c-55d1f7535133.png)

**Comment by johnGachihi** [comment]
:see_no_evil: I just noticed that the Eventbrite API also returns a url for the original uncropped event image. And the images are big enough to not get pixelated. I'll send a PR soon.

![Screenshot from 2023-01-24 20-05-22](https://user-images.githubusercontent.com/25545884/214360059-d7f43054-0d65-4609-ab6f-5eb3ee777e9c.png)
