### ISSUE TITLE
Make the Footer have dynamic events as well

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#38]
The footer has a section that has some events,
we should make those dynamic, with the events being fetched in the homepage, it should not be hard!

**Comment by EspiraMarvin** [comment]
@katungi Assign me this. Also noticed the footer has no good padding in extra large screens. I can fix that.

**Comment by katungi** [comment]
Awesome work @EspiraMarvin , Thank you so much!
