### ISSUE TITLE
Fix layout issue on Homepage

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#39]
Between the events component, and the Blogs component, there is some huge space.
This can only be observed when viewing in mobile.

**Comment by g-nm** [comment]
Hey @katungi  I would like to pick this issue

**Comment by katungi** [comment]
Hey @g-nm , go ahead and fix it ⚡

**Comment by g-nm** [comment]
Shared the fix here is my before and after the fix 
**Before*
![before](https://user-images.githubusercontent.com/43496216/179499630-6c68e319-fcb4-4397-9e36-5b2f8d510268.png)
*
**After* 
![after](https://user-images.githubusercontent.com/43496216/179499699-edcf0938-eaae-4db2-8846-1a9a79285d5a.png)

**Comment by katungi** [comment]
This is perfect @g-nmm, thanks for this!
