### ISSUE TITLE
Create the Banner component

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#4]
The banner component should live in the `/component` folder in the root directory.
This task might need more than one contributor so if you feel limited to work on it or might need help on it, make sure to reach out to the maintainers.

- The banner component must match the designs as shown below
![banner](https://user-images.githubusercontent.com/26451435/173342771-9d5eb588-7a61-4c7d-a81f-e919b630b033.png)

- The second bit with the image should be responsive. If the user is on mobile, the image should disappear and just leave the text.

This task should take a short time as well, so that we can finish the first sprint with it.

In-case of any blockers, be sure to ping the maintainers.

**Comment by katungi** [comment]
Sure thing @johnGachihi , Take a stab at it. How long do you think it will take?

**Comment by johnGachihi** [comment]
I've already made good progress, so I should be able to submit something for review today

**Comment by alexmagwe** [comment]
I would like to make a suggestion to animate the "learn, grow, connect" header.

**Comment by katungi** [comment]
Hey @alexmagwe , that's a really great idea. What animation do you suggest?
Could you maybe provide a sample ?

**Comment by alexmagwe** [comment]
I was thinking a text typing animation with only one word of the phrase being shown at a time

**Comment by VeldaKiara** [comment]
hey @alexmagwe and @katungi that's good a idea, I am on board
