### ISSUE TITLE
Add Typings to the event response object for best typescript practices.

### ISSUE THREAD

**Issue by EspiraMarvin** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#41]
The event from the events endpoint response has type any.
Intending to add typings to the event response object for best typescript practices, and also help in response intelligent code autocompletion

**Comment by katungi** [comment]
Hey @EspiraMarvin , thanks for catching that, actually, I noticed lots of ambiguous type annotations in the project. Mind making sure everything looks good type-wise?

**Comment by EspiraMarvin** [comment]
@katungi Don't mind, also would use interfaces instead of types, since interfaces can be extended

**Comment by katungi** [comment]
Thanks for fixing this @EspiraMarvin!
