### ISSUE TITLE
Change images on banner to fit the design

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#7]
One of the contributors did an amazing job working on the banner. Shoutout to @johnGachihi.

We however need help adding the correct images on the banners. This should be a good first issue 🥳

**Comment by Murathe** [comment]
Are the images supposed to be overlapping on each other or they coming bundled together as a single .png?

**Comment by 3stherMueni** [comment]
@M-Tee kindly have a look at this

**Comment by M-Tee** [comment]
@3stherMueni @mevolkan I've updated the file with images without the borders. They are right above the desktop landing page design.

**Comment by mevolkan** [comment]
much better, thank you @M-Tee 
![Screenshot 2022-06-24 at 13 37 11](https://user-images.githubusercontent.com/16579273/175518401-fd8805fd-ad8d-4d90-a3bf-ff997be4c76b.png)

**Comment by katungi** [comment]
Thanks @mevolkan , and @M-Tee, Closing this issue because it has been solved!
