### ISSUE TITLE
Build out the call to action banner

### ISSUE THREAD

**Issue by katungi** [SheCodeAfrica-Nairobi/SheCodeAfrica-Nairobi-Website#8]
The next section is to add a call to action banner ( For lack of a better word ) 😅
![call to action](https://user-images.githubusercontent.com/26451435/174769827-364b84ed-1a1e-4c1e-b36d-3ffd2ed4902c.png)

Note:
Pay close attention to the colours and the padding of the component. It should be centered.

**Comment by Mogakamo** [comment]
@katungi I want to handle this

**Comment by Mogakamo** [comment]
ok cool

**Comment by katungi** [comment]
Bless you @Mogakamo , amazing work!
